In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import datetime as dt
import tensorflow as tf
from sklearn.preprocessing import RobustScaler, MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error
from tensorflow.keras import Sequential # Deep learning library, used for neural networks
from tensorflow.keras.layers import LSTM, Dense, Dropout # Deep learning classes for recurrent and regular densely-connected layers
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint # EarlyStopping during model training
from tensorflow.keras.optimizers import Adam
import math


import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/testvalidation/Test.csv
/kaggle/input/etherum-2022-minbymin/ETHUSDT_Binance_futures_2022_minute.csv
/kaggle/input/real-validation/Day 2.csv
/kaggle/input/real-validation/Day 3.csv
/kaggle/input/real-validation/Day 1.csv
/kaggle/input/real-validation/Day 5.csv
/kaggle/input/real-validation/Day 4.csv
/kaggle/input/real-validation/Day 7.csv
/kaggle/input/real-validation/Day 6.csv
/kaggle/input/etherum-model/Ethereum_Model/saved_model.pb
/kaggle/input/etherum-model/Ethereum_Model/keras_metadata.pb
/kaggle/input/etherum-model/Ethereum_Model/variables/variables.index
/kaggle/input/etherum-model/Ethereum_Model/variables/variables.data-00000-of-00001
/kaggle/input/etherum/ETH-USD.csv
/kaggle/input/eth-updated/Ethereum_Updated_Model/saved_model.pb
/kaggle/input/eth-updated/Ethereum_Updated_Model/keras_metadata.pb
/kaggle/input/eth-updated/Ethereum_Updated_Model/variables/variables.index
/kaggle/input/eth-updated/Ethereum_Updated_Model/variables/variables.data-00000-of-00001
/kaggl

# This file is used as a test enviroment to build the perfect LSTM model with high accuracy.

In [6]:
df = pd.read_csv('/kaggle/input/etherum-2022-minbymin/ETHUSDT_Binance_futures_2022_minute.csv')
# Removing all unessesary columns ( See Research )
df = df = df.drop(["Volume ETH", "unix","Volume USDT", "symbol","open","tradecount"], axis=1)
df['date'] = pd.to_datetime(df['date'])
df = df.sort_values(by='date')
df.index = df.pop("date")
df

high      low    close
date                                          
2022-01-01 00:01:00  3692.29  3681.11  3690.61
2022-01-01 00:02:00  3692.94  3685.66  3692.00
2022-01-01 00:03:00  3693.93  3688.21  3689.25
2022-01-01 00:04:00  3689.69  3686.55  3688.53
2022-01-01 00:05:00  3698.26  3685.00  3697.77
...                      ...      ...      ...
2022-09-07 00:12:00  1562.67  1561.08  1561.09
2022-09-07 00:13:00  1561.98  1560.01  1560.99
2022-09-07 00:14:00  1562.00  1560.50  1560.88
2022-09-07 00:15:00  1562.76  1560.58  1561.51
2022-09-07 00:16:00  1561.50  1555.82  1556.24

[358576 rows x 3 columns]

In [8]:
# Scaler for N-Dimensional Array
df_features = df
df_np = df_features.to_numpy()
scaler = MinMaxScaler()
df_scaled = scaler.fit_transform(df_np, (-1,1))
df_scaled[0]

array([0.93307773, 0.93242654, 0.93452141])

In [9]:
# Scaler for 1D array
df_close = pd.DataFrame(df['close'])
df_close_np = df_close.to_numpy()
to_inverse_scale = MinMaxScaler()
df_close_scale = to_inverse_scale.fit_transform(df_close_np)
df_close_scale

array([[0.93452141],
       [0.93498417],
       [0.93406864],
       ...,
       [0.22549297],
       [0.22570271],
       [0.22394822]])

In [ ]:
x = [] # The features needed for prediction.
y = [] # The expected result.

for i in range(len(df_scaled)-7):
    x.append(df_scaled[i:i+7])

for i in range(len(df_close_scale)-1):
        y.append(df_close_scale[i][0])


# Converting to Numpy array for easier reading by the ML-Algorithm
X = np.array(x)
Y = np.array(y)

In [ ]:
train_no = math.floor(len(X) * 0.7) # 70% for training, 30% For Testing
total_no = len(X) 
X_Train, Y_Train = X[:train_no][:train_no], Y[:train_no]
X_Test, Y_Test = X[train_no: total_no - 1], Y[train_no: total_no - 1]
print(X_Train.shape, Y_Train.shape)
print(X_Test.shape, Y_Test.shape)

# Model#1

# Model#2

In [ ]:
model2 = Sequential()
# 8 layers, Final Output is in an array of 1 predictions
model2.add(LSTM(200, return_sequences=True, input_shape=(7,3)))
model2.add(LSTM(150, return_sequences=True))
model2.add(LSTM(100, return_sequences=True))
model2.add(LSTM(50, return_sequences=False))
model2.add(Dense(15))
model2.add(Dense(10))
model2.add(Dense(5))
model2.add(Dense(1))

In [ ]:
model3 = Sequential()
# Final Output is in an array of 1 predictions
model3.add(LSTM(300, return_sequences=True, input_shape=(7,3)))
model3.add(LSTM(250, return_sequences=True))
model3.add(LSTM(200, return_sequences=True))
model3.add(LSTM(150, return_sequences=True))
model3.add(LSTM(100, return_sequences=True))
model3.add(LSTM(50, return_sequences=False))
model3.add(Dense(20))
model3.add(Dense(15))
model3.add(Dense(10))
model3.add(Dense(5))
model3.add(Dense(1))

# Model 4

In [ ]:
model4 = Sequential()

model4.add(LSTM(300, return_sequences=True, input_shape=(7,3)))
model4.add(LSTM(250, return_sequences=True))
model4.add(LSTM(200, return_sequences=True))
model4.add(LSTM(150, return_sequences=True))
model4.add(LSTM(100, return_sequences=True))
model4.add(LSTM(50, return_sequences=False))
model4.add(Dense(25))
model4.add(Dense(20))
model4.add(Dense(15))
model4.add(Dense(10))
model4.add(Dense(5))
model4.add(Dense(1))

# Model 5

In [12]:
model5 = Sequential()
model5.add(LSTM(400, return_sequences=True, input_shape=(7,3)))
model5.add(LSTM(350, return_sequences=True))
model5.add(LSTM(300, return_sequences=True))
model5.add(LSTM(250, return_sequences=True))
model5.add(LSTM(200, return_sequences=True))
model5.add(LSTM(150, return_sequences=True))
model5.add(LSTM(100, return_sequences=True))
model5.add(LSTM(50, return_sequences=False))
model5.add(Dense(30))
model5.add(Dense(25))
model5.add(Dense(20))
model5.add(Dense(15))
model5.add(Dense(10))
model5.add(Dense(5))
model5.add(Dense(1))

# Gets the current models structure.

In [13]:
model5.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 7, 400)            646400    
_________________________________________________________________
lstm_1 (LSTM)                (None, 7, 350)            1051400   
_________________________________________________________________
lstm_2 (LSTM)                (None, 7, 300)            781200    
_________________________________________________________________
lstm_3 (LSTM)                (None, 7, 250)            551000    
_________________________________________________________________
lstm_4 (LSTM)                (None, 7, 200)            360800    
_________________________________________________________________
lstm_5 (LSTM)                (None, 7, 150)            210600    
_________________________________________________________________
lstm_6 (LSTM)                (None, 7, 100)            1

# Compiliation and Fitting Model

In [ ]:
model2.compile(optimizer="Adam", loss='mean_squared_error') # Compling the Model
callback = [EarlyStopping(monitor='loss', patience=10, verbose=1, mode='min')] # Stops from overfitting
modeled = model2.fit(X_Train, Y_Train, batch_size=500, epochs=100, callbacks=callback) # Training the

# Predictions

In [ ]:
#x = X_Test.reshape(-1,1)
predictions = model2.predict(X_Test)
predictions = to_inverse_scale.inverse_transform(predictions) # Reverse the standardization.
#predictions
# Putting the predictions in an array to convert into dataframe column later.
valid = []
for i in range(len(predictions)):
    valid.append(predictions[i][0]) # Using the final prediction in the array.

In [ ]:
new_df = pd.DataFrame(df[train_no: total_no - 1])
new_df = new_df.drop(["high","low"], axis=1)
new_df['Prediction'] = valid


new_df

In [ ]:
new_df.plot()

In [ ]:
new_df.corr()

# Validation

In [ ]:
import matplotlib.pyplot as plt


#print(mean(modeled.history['mse']))
#print(mean(modeled.history['mape']))
#print(mean(modeled.history['rmse']))


from sklearn.metrics import mean_absolute_percentage_error
from sklearn.metrics import mean_absolute_error
mape = mean_absolute_percentage_error(new_df['close'].values, new_df['Prediction'].values)
mae = mean_absolute_error(new_df['close'].values, new_df['Prediction'].values)
print(mape)
print(mae)

In [ ]:
model2.save('myTestModel')


# Testing Independant Enviroment
The model ceases to exist above and is load below using TensorFlow functions.

In [ ]:
df = pd.read_csv('../input/etherum/ETH-USD.csv')
new_df = pd.read_csv('../input/etherum/ETH-USD.csv')
# Removing all unessesary columns ( See Research )
df = df.drop(["Volume", "Adj Close","Open"], axis=1)
new_df = new_df.drop(["Volume", "High", "Low","Adj Close","Open"], axis=1)
df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values(by='Date')
df.index = df.pop("Date")

df

In [ ]:
df_np = df.to_numpy()
scaler = MinMaxScaler()
df_scaled = scaler.fit_transform(df_np, (-1,1))
df_scaled.shape

In [ ]:
test = []

for i in range(len(df_scaled)-7):
    test.append(df_scaled[i:i+7])
    
test = np.array(test)



In [ ]:
test.shape

In [ ]:
new_model = tf.keras.models.load_model('/kaggle/input/etherum-model/Ethereum_Model')
new_model.summary()

In [ ]:
prediction = new_model.predict(test)
prediction = to_inverse_scale.inverse_transform(prediction) 

predictions
valid = []
for i in range(len(prediction)):
    valid.append(prediction[i][0]) 

In [ ]:
#new_df = pd.read_csv('/kaggle/input/btcdata/BTC-USD.csv')
new_df = df[:359]
new_df = new_df.drop([ "High", "Low"], axis=1)
new_df['Prediction'] = valid


new_model.summary()

In [ ]:
new_df.plot()

In [ ]:
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.metrics import mean_absolute_error
mape = mean_absolute_percentage_error(new_df['Close'].values, new_df['Prediction'].values)
mae = mean_absolute_error(new_df['Close'].values, new_df['Prediction'].values)
print(mape)
print(mae)

In [ ]:
new_df.corr()

In [10]:
def loadDataPrediction(df_test):
    df = df_test
    real_df = df.drop(["Volume","Adj Close","Open"], axis=1)
    real_df['Date'] = pd.to_datetime(real_df['Date'])
    real_df = real_df.sort_values(by='Date')
    real_df.index = real_df.pop("Date")
    
    scaler = MinMaxScaler()
    df_scaled = scaler.fit_transform(real_df, (-1,1))
    n_df = df_scaled.reshape(1,7,3)
    print(n_df.shape)
    test =  new_model.predict(n_df)
    test = to_inverse_scale.inverse_transform(test)
    
    return test

def customUnitTest(actual, pred):
    mape = mean_absolute_percentage_error(actual, pred)
    
    if( mape <= 0.2):
        print("Passed Test: 7")
        print(mape)
    else:
        print("Failed Test: 7")
        print(mape)

In [11]:
day1_df = pd.read_csv('/kaggle/input/real-validation/Day 1.csv')
day2_df = pd.read_csv('/kaggle/input/real-validation/Day 2.csv')
day3_df = pd.read_csv('/kaggle/input/real-validation/Day 3.csv')
day4_df = pd.read_csv('/kaggle/input/real-validation/Day 4.csv')
day5_df = pd.read_csv('/kaggle/input/real-validation/Day 5.csv')
day6_df = pd.read_csv('/kaggle/input/real-validation/Day 6.csv')
day7_df = pd.read_csv('/kaggle/input/real-validation/Day 7.csv')


test = pd.read_csv('/kaggle/input/valid-or-not/ETH-USD.csv')



day_1 = loadDataPrediction(test)
day_2 = loadDataPrediction(day2_df)
day_3 = loadDataPrediction(day3_df)
day_4 = loadDataPrediction(day4_df)
day_5 = loadDataPrediction(day5_df)
day_6 = loadDataPrediction(day6_df)
day_7 = loadDataPrediction(day7_df)

pred = [day_1[0][0], day_2[0][0], day_3[0][0], day_4[0][0], day_5[0][0], day_6[0][0], day_7[0][0]]
#print(pred)
#print(day_1)
#print(test['Close'])
day_1
#customUnitTest(test['Close'].values, pred)

(1, 7, 3)
(1, 7, 3)
(1, 7, 3)
(1, 7, 3)
(1, 7, 3)
(1, 7, 3)
(1, 7, 3)


array([[2212.7468]], dtype=float32)